### ISSUE TITLE
회사와 채용공고 테이블 만들기

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/wanted_pre_onboarding#2]
### Summary
Company 폴더를 한개를 만들고 URL 설정을 해줍니다. 그리고 회사와 채용공고 테이블을 만들어줍니다..

### TODO
- [x] Company 폴더 생성
- [x] URL 설정
- [x] Company DB 만들기
- [x] Job_Posting DB 만들기
