### ISSUE TITLE
Company와 JobPosting의 CRUD 구성

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/wanted_pre_onboarding#4]
### Summary
Company는 ReadOnlyModel로 설정을 해서 보는건만 지정을 하고
Job_Posting DB는 post, put, delete를 설정을 해줍니다.

### TODO
- [x] Company Serializer랑 Job_Posting Serializer 만듬
- [x] Company view랑 Job_Posting view만듬
- [x] URL 설정
- [x] https://localhost/companys 구성
- [x] https://localhost/companys/1/job_postings 구성
- [x] https://localhost/job_postrings 구성
